persistence:
  persistentVolumeClaim:
    registry:
      size: 10Gi
    database:
      size: 5Gi
nginx:
  resources:
    requests:
      cpu: 0.05
      memory: 128Mi
    limits:
      cpu: 0.1
      memory: 256Mi

portal:
  resources:
    requests:
      cpu: 0.05
      memory: 128Mi
    limits:
      cpu: 0.1
      memory: 256Mi

core:
  resources:
    requests:
      cpu: 0.05
      memory: 128Mi
    limits:
      cpu: 0.1
      memory: 256Mi

jobservice:
  resources:
    requests:
      cpu: 0.05
      memory: 128Mi
    limits:
      cpu: 0.1
      memory: 256Mi

registry:
  registry:
    resources:
      image:
        requests:
          cpu: 0.05
          memory: 8196Mi
      controller:
        limits:
          cpu: 0.1
          memory: 10808Mi
 
chartmuseum:
  resources:
    requests:
      cpu: 0.05
      memory: 50Mi
    limits:
      cpu: 0.1
      memory: 100Mi

trivy:
  resources:
    requests:
      cpu: 0.2
      memory: 512Mi
    limits:
      cpu: 1
      memory: 1Gi


notary:
  server:
    resources:
      requests:
        cpu: 0.01
        memory: 20Mi
      limits:
        cpu: 0.02
        memory: 40Mi
  signer:
    resources:
      requests:
        cpu: 0.01
        memory: 20Mi
      limits:
        cpu: 0.02
        memory: 40Mi

database:
  internal:
    resources:
      requests:
        cpu: 0.02
        memory: 400Mi
      limits:
        cpu: 0.04
        memory: 800Mi

redis:
  resources:
    requests:
      cpu: 0.01
      memory: 15Mi
    limits:
      cpu: 0.02
      memory: 30Mi
